#!/usr/local/php70/bin/php
<?php
if ($argc < 2) {
    usage();
}

$zts = $world = false;
$build = [];
$conf = [];

$version = preg_replace('/[\.\-]+/', '', $argv[1]);

function usage()
{
    $cmd = basename(__FILE__);
    echo "Usage: $cmd 73|72|71|70|7X|56|all|world [zts]\n";
    echo "To rebuild PHP 7.2 and 7.2-debug: $cmd 72\n";
    echo "To rebuild PHP 7.2 and 7.2-debug threadsafe: $cmd 72 zts\n";
    echo "To rebuild all PHP 7 versions: $cmd 7X\n";
    exit;
}

if (!empty($argv[2]) && $argv[2] == 'zts') {
    $zts = true;
}

switch ($argv[1]) {
    case '73':
        $build[73] = true;
        break;
    case '7':
    case '72':
        $build[72] = true;
        break;
    case '71':
        $build[71] = true;
        break;
    case '70':
        $build[7] = true;
        break;
    case '7X':
        $build = [73 => true, 72 => true, 71 => true, 7 => true];
        break;
    case '5':
    case '56':
        $build[56] = true;
        break;
    case 'all':
        $build = [73 => true, 72 => true, 71 => true, 7 => true, 56 => true];
        break;
    case 'world':
        $build = [72 => true, 71 => true, 7 => true, 56 => true];
        $world = true;
        break;
}

$conf[73] = [
    '--with-apxs2=/usr/bin/apxs2',
    '--enable-zend-signals',
    '--with-gd',
    '--with-jpeg-dir=/usr',
    '--with-png-dir=/usr',
    '--with-vpx-dir=/usr',
    '--with-freetype-dir=/usr',
    '--with-t1lib=/usr',
    '--enable-gd-native-ttf',
    '--enable-exif',
    '--with-config-file-path=/etc/php73',
    '--with-config-file-scan-dir=/etc/php73/conf.d',
    '--with-mysql-sock=/var/run/mysqld/mysqld.sock',
    '--with-zlib',
    '--enable-phpdbg',
    '--with-gmp',
    '--with-zlib-dir=/usr',
    '--with-gettext',
    '--with-kerberos',
    '--with-imap-ssl',
    '--with-sodium=/usr/local/lib',
    '--with-iconv',
    '--enable-sockets',
    '--with-openssl',
    '--with-pspell',
    '--with-pdo-mysql=mysqlnd',
    '--with-pdo-sqlite',
    '--with-pgsql',
    '--with-pdo-pgsql',
    '--enable-soap',
    '--enable-xmlreader',
    '--enable-phar=shared',
    '--with-xsl',
    '--enable-ftp',
    '--enable-cgi',
    '--with-curl=/usr',
    '--with-tidy',
    '--with-xmlrpc',
    '--enable-mbstring',
    '--enable-sysvsem',
    '--enable-sysvshm',
    '--enable-shmop',
    '--with-readline',
    '--enable-pcntl',
    '--enable-fpm',
    '--with-fpm-systemd',
    '--enable-intl',
    '--enable-zip',
    '--with-imap',
    '--with-mysqli=mysqlnd',
    '--enable-calendar',
    '--enable-bcmath',
    '--enable-opcache-file'
];

$conf[72] = [
    '--with-apxs2=/usr/bin/apxs2',
    '--enable-zend-signals',
    '--with-gd',
    '--with-jpeg-dir=/usr',
    '--with-png-dir=/usr',
    '--with-vpx-dir=/usr',
    '--with-freetype-dir=/usr',
    '--with-t1lib=/usr',
    '--enable-gd-native-ttf',
    '--enable-exif',
    '--with-config-file-path=/etc/php72',
    '--with-config-file-scan-dir=/etc/php72/conf.d',
    '--with-mysql-sock=/var/run/mysqld/mysqld.sock',
    '--with-zlib',
    '--enable-phpdbg',
    '--with-gmp',
    '--with-zlib-dir=/usr',
    '--with-gettext',
    '--with-kerberos',
    '--with-imap-ssl',
    '--with-sodium=/usr/local/lib',
    '--with-iconv',
    '--enable-sockets',
    '--with-openssl',
    '--with-pspell',
    '--with-pdo-mysql=mysqlnd',
    '--with-pdo-sqlite',
    '--with-pgsql',
    '--with-pdo-pgsql',
    '--enable-soap',
    '--enable-xmlreader',
    '--enable-phar=shared',
    '--with-xsl',
    '--enable-ftp',
    '--enable-cgi',
    '--with-curl=/usr',
    '--with-tidy',
    '--with-xmlrpc',
    '--enable-mbstring',
    '--enable-sysvsem',
    '--enable-sysvshm',
    '--enable-shmop',
    '--with-readline',
    '--enable-pcntl',
    '--enable-fpm',
    '--with-fpm-systemd',
    '--enable-intl',
    '--enable-zip',
    '--with-imap',
    '--with-mysqli=mysqlnd',
    '--enable-calendar',
    '--enable-bcmath',
    '--enable-opcache-file'
];

$conf[71] = [
    '--with-apxs2=/usr/bin/apxs2',
    '--enable-zend-signals',
    '--with-gd',
    '--with-jpeg-dir=/usr',
    '--with-png-dir=/usr',
    '--with-vpx-dir=/usr',
    '--with-freetype-dir=/usr',
    '--with-t1lib=/usr',
    '--enable-gd-native-ttf',
    '--enable-exif',
    '--with-config-file-path=/etc/php71',
    '--with-config-file-scan-dir=/etc/php71/conf.d',
    '--with-mysql-sock=/var/run/mysqld/mysqld.sock',
    '--with-zlib',
    '--enable-phpdbg',
    '--with-gmp',
    '--with-zlib-dir=/usr',
    '--with-gettext',
    '--with-kerberos',
    '--with-imap-ssl',
    '--with-mcrypt=/usr/local',
    '--with-iconv',
    '--enable-sockets',
    '--with-openssl',
    '--with-pspell',
    '--with-pdo-mysql=mysqlnd',
    '--with-pdo-sqlite',
    '--with-pgsql',
    '--with-pdo-pgsql',
    '--enable-soap',
    '--enable-xmlreader',
    '--enable-phar=shared',
    '--with-xsl',
    '--enable-ftp',
    '--enable-cgi',
    '--with-curl=/usr',
    '--with-tidy',
    '--with-xmlrpc',
    '--enable-mbstring',
    '--enable-sysvsem',
    '--enable-sysvshm',
    '--enable-shmop',
    '--with-readline',
    '--enable-pcntl',
    '--enable-fpm',
    '--with-fpm-systemd',
    '--enable-intl',
    '--enable-zip',
    '--with-imap',
    '--with-mysqli=mysqlnd',
    '--enable-calendar',
    '--enable-bcmath',
    '--enable-opcache-file'
];

$conf[7] = [
    '--with-apxs2=/usr/bin/apxs2',
    '--enable-zend-signals',
    '--with-gd',
    '--with-jpeg-dir=/usr',
    '--with-png-dir=/usr',
    '--with-vpx-dir=/usr',
    '--with-freetype-dir=/usr',
    '--with-t1lib=/usr',
    '--enable-gd-native-ttf',
    '--enable-exif',
    '--with-config-file-path=/etc/php7',
    '--with-config-file-scan-dir=/etc/php7/conf.d',
    '--with-mysql-sock=/var/run/mysqld/mysqld.sock',
    '--with-zlib',
    '--enable-phpdbg',
    '--with-gmp',
    '--with-zlib-dir=/usr',
    '--with-gettext',
    '--with-kerberos',
    '--with-imap-ssl',
    '--with-mcrypt=/usr/local',
    '--with-iconv',
    '--enable-sockets',
    '--with-openssl',
    '--with-pspell',
    '--with-pdo-mysql=mysqlnd',
    '--with-pdo-sqlite',
    '--with-pgsql',
    '--with-pdo-pgsql',
    '--enable-soap',
    '--enable-xmlreader',
    '--enable-phar=shared',
    '--with-xsl',
    '--enable-ftp',
    '--enable-cgi',
    '--with-curl=/usr',
    '--with-tidy',
    '--with-xmlrpc',
    '--enable-mbstring',
    '--enable-sysvsem',
    '--enable-sysvshm',
    '--enable-shmop',
    '--with-readline',
    '--enable-pcntl',
    '--enable-fpm',
    '--with-fpm-systemd',
    '--enable-intl',
    '--enable-zip',
    '--with-imap',
    '--with-mysqli=mysqlnd',
    '--enable-calendar',
    '--enable-bcmath',
    '--enable-opcache-file'
];

$conf[56] = [
    '--with-apxs2=/usr/bin/apxs2',
    '--enable-zend-signals',
    '--with-gd',
    '--with-jpeg-dir=/usr',
    '--with-png-dir=/usr',
    '--with-vpx-dir=/usr',
    '--with-freetype-dir=/usr',
    '--with-t1lib=/usr',
    '--enable-gd-native-ttf',
    '--enable-exif',
    '--with-config-file-path=/etc/php56',
    '--with-config-file-scan-dir=/etc/php56/conf.d',
    '--with-mysql=/usr',
    '--with-mysql-sock=/var/run/mysqld/mysqld.sock',
    '--with-zlib',
    '--with-gmp',
    '--with-zlib-dir=/usr',
    '--with-gettext',
    '--with-kerberos',
    '--with-imap-ssl',
    '--with-mcrypt=/usr/local',
    '--with-iconv',
    '--enable-sockets',
    '--with-openssl',
    '--with-pspell',
    '--with-pdo-mysql=mysqlnd',
    '--with-pdo-sqlite',
    '--with-pgsql',
    '--with-pdo-pgsql',
    '--enable-soap',
    '--enable-zip',
    '--enable-xmlreader',
    '--enable-phar=shared',
    '--with-xsl',
    '--enable-ftp',
    '--enable-cgi',
    '--with-curl=/usr',
    '--with-tidy',
    '--with-xmlrpc',
    '--enable-mbstring',
    '--enable-sysvsem',
    '--enable-sysvshm',
    '--enable-shmop',
    '--with-readline',
    '--enable-pcntl',
    '--enable-fpm',
    '--enable-intl',
    '--with-imap',
    '--with-mysqli=mysqlnd',
    '--enable-calendar',
    '--enable-bcmath'
];

function build_it($branch, $conf_flags)
{
    $cmds = [
        "git checkout $branch",
        "git fetch --all 2>&1 1> /dev/null",
        "git reset --hard origin/$branch 2>&1 1> /dev/null",
        "git pull -r",
        "./vcsclean 2>&1 1> /dev/null",
        "./buildconf --force",
        "=configuring...",
        "./configure $conf_flags 2>&1 1>> /tmp/build.log",
        "=\ncompiling...",
        "make -j2 2>&1 1>> /tmp/build.log",
        "=\ninstalling...",
        "sudo make install 2>&1 1>> /tmp/build.log",
        "=\ndone\n"
    ];
    foreach ($cmds as $cmd) {
        if ($cmd[0] == '=') {
            echo substr($cmd, 1);
        } else {
            shell_exec($cmd);
        }
    }
}

$dir = getcwd();
chdir("/home/vagrant/php-src");
shell_exec("truncate --size 0 /tmp/build.log");
echo "Build log in /tmp/build.log\n";

foreach ($build as $v => $b) {
    switch ($v) {
        case 73:
            if (!$zts || $world) {
                echo "Building PHP 7.3\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --disable-debug --prefix=/usr/local/php73';
                build_it('PHP-7.3', $conf_flags);
                echo "Building PHP 7.3-debug\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --enable-debug --prefix=/usr/local/php73-debug';
                build_it('PHP-7.3', $conf_flags);
            }
            if ($zts || $world) {
                echo "Building PHP 7.3-zts\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --disable-debug --enable-maintainer-zts --prefix=/usr/local/php73-zts';
                build_it('PHP-7.3', $conf_flags);
                echo "Building PHP 7.3-debug-zts\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --enable-debug --enable-maintainer-zts --prefix=/usr/local/php73-debug-zts';
                build_it('PHP-7.3', $conf_flags);
            }
            break;

        case 72:
            if (!$zts || $world) {
                echo "Building PHP 7.2\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --disable-debug --prefix=/usr/local/php72';
                build_it('PHP-7.2', $conf_flags);
                echo "Building PHP 7.2-debug\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --enable-debug --prefix=/usr/local/php72-debug';
                build_it('PHP-7.2', $conf_flags);
            }
            if ($zts || $world) {
                echo "Building PHP 7.2-zts\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --disable-debug --enable-maintainer-zts --prefix=/usr/local/php72-zts';
                build_it('PHP-7.2', $conf_flags);
                echo "Building PHP 7.2-debug-zts\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --enable-debug --enable-maintainer-zts --prefix=/usr/local/php72-debug-zts';
                build_it('PHP-7.2', $conf_flags);
            }
            break;

        case 71:
            if (!$zts || $world) {
                echo "Building PHP 7.1\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --disable-debug --prefix=/usr/local/php71';
                build_it('PHP-7.1', $conf_flags);
                echo "Building PHP 7.1-debug\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --enable-debug --prefix=/usr/local/php71-debug';
                build_it('PHP-7.1', $conf_flags);
            }
            if ($zts || $world) {
                echo "Building PHP 7.1-zts\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --disable-debug --enable-maintainer-zts --prefix=/usr/local/php71-zts';
                build_it('PHP-7.1', $conf_flags);
                echo "Building PHP 7.1-debug-zts\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --enable-debug --enable-maintainer-zts --prefix=/usr/local/php71-debug-zts';
                build_it('PHP-7.1', $conf_flags);
            }
            break;

        case 7:
            if (!$zts || $world) {
                echo "Building PHP 7.0\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --disable-debug --prefix=/usr/local/php70';
                build_it('PHP-7.0', $conf_flags);
                echo "Building PHP 7.0-debug\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --enable-debug --prefix=/usr/local/php70-debug';
                build_it('PHP-7.0', $conf_flags);
            }
            if ($zts || $world) {
                echo "Building PHP 7.0-zts\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --disable-debug --enable-maintainer-zts --prefix=/usr/local/php70-zts';
                build_it('PHP-7.0', $conf_flags);
                echo "Building PHP 7.0-debug-zts\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --enable-debug --enable-maintainer-zts --prefix=/usr/local/php70-debug-zts';
                build_it('PHP-7.0', $conf_flags);
            }
            break;

        case 56:
            if (!$zts || $world) {
                echo "Building PHP 5.6\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --disable-debug --prefix=/usr/local/php56';
                build_it('PHP-5.6', $conf_flags);
                echo "Building PHP 5.6-debug\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --enable-debug --prefix=/usr/local/php56-debug';
                build_it('PHP-5.6', $conf_flags);
            }
            if ($zts || $world) {
                echo "Building PHP 5.6-zts\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --disable-debug --enable-maintainer-zts --prefix=/usr/local/php56-zts';
                build_it('PHP-5.6', $conf_flags);
                echo "Building PHP 5.6-debug-zts\n";
                $conf_flags = implode(' ', $conf[$v]) . ' --enable-debug --enable-maintainer-zts --prefix=/usr/local/php56-debug-zts';
                build_it('PHP-5.6', $conf_flags);
            }
            break;
    }
}
